#!/bin/bash

version=`grep -m 1 'version := ' bsnes/Makefile | awk '{ print $3 }'`;
bsnes_version=bsnes+${version}
dist_dir=distribution

#clean & set up distribution directory
rm -f ${dist_dir}/${bsnes_version}.zip
rm -frd ${dist_dir}/${bsnes_version}
mkdir -pv ${dist_dir}/${bsnes_version}
cp -a bsnes/data/bsxdat ${dist_dir}/${bsnes_version}/bsxdat

#build app bundles
make all
mv ./bsnes+.app ${dist_dir}/${bsnes_version}/bsnes+.app
mv ./bsnes+accuracy.app ${dist_dir}/${bsnes_version}/bsnes+accuracy.app

#zip distribution directory
pushd ${dist_dir}
zip -r -y -9 ${bsnes_version}_osx.zip ${bsnes_version}
popd

#clean up
make clean
